website/web/docker_django/apps/landing_page/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='landing_page'),
    url(r'^the-team$', views.the_team, name='the_team'),
    url(r'^research$', views.research, name='research'),
    url(r'^tools$', views.tools, name='tools'),
    url(r'^publications$', views.publications, name='publications'),
    url(r'^publication/(?P<pk>\d+)/$', views.publication_detail, name='publication_detail'),
    url(r'^publication/(?P<pk>\d+)/edit/$', views.edit_publication, name='edit_publication'),
    url(r'^publication/(?P<pk>\d+)/remove/$', views.remove_publication, name='remove_publication'),
    url(r'^pubmed_search$', views.pubmed_search, name='pubmed_search'),
    url(r'^member$', views.member, name='member'),
    url(r'^member/edit-profile/$', views.edit_profile, name='edit_profile'),
    url(r'^member/analysis$', views.analysis, name='analysis'),
]

website/web/docker_django/apps/todo/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.list_lists, name="todo-lists"),
    url(r'^mine/$', views.view_list, {'list_slug': 'mine'}, name="todo-mine"),
    url(r'^(?P<list_id>\d{1,4})/(?P<list_slug>[\w-]+)/delete$', views.del_list, name="todo-del_list"),
    url(r'^task/(?P<task_id>\d{1,6})$', views.view_task, name='todo-task_detail'),
    url(r'^(?P<list_id>\d{1,4})/(?P<list_slug>[\w-]+)$', views.view_list, name='todo-incomplete_tasks'),
    url(r'^(?P<list_id>\d{1,4})/(?P<list_slug>[\w-]+)/completed$', views.view_list, {'view_completed': True},
        name='todo-completed_tasks'),
    url(r'^add_list/$', views.add_list, name="todo-add_list"),
    url(r'^search-post/$', views.search_post, name="todo-search-post"),
    url(r'^search/$', views.search, name="todo-search"),

    # View reorder_tasks is only called by JQuery for drag/drop task ordering
    url(r'^reorder_tasks/$', views.reorder_tasks, name="todo-reorder_tasks"),

    url(r'^ticket/add/$', views.external_add, name="todo-external-add"),
    url(r'^recent/added/$', views.view_list, {'list_slug': 'recent-add'}, name="todo-recently_added"),
    url(r'^recent/completed/$', views.view_list, {'list_slug': 'recent-complete'},
        name="todo-recently_completed"),
]

website/web/docker_django/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('docker_django.apps.landing_page.urls')),
    url(r'^databases/', include('docker_django.apps.databases.urls')),
    url(r'^news/', include('docker_django.apps.news.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'landing_page/home.html'}),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^todo/', include('docker_django.apps.todo.urls')),
    )

website/web/docker_django/apps/landing_page/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime



#########################################################################################################
# site wide announcements
LEVEL_CHOICES = (
     ('warning', 'Warning'),
     ('danger', 'Danger'),
     ('success', 'Success'),
     ('info', 'Info'),
)
class Announcement(models.Model):
    """
    Model to hold global announcements
    """
    body = models.TextField(blank=False)
    display = models.BooleanField(default=False)
    level = models.CharField(max_length=8, choices=LEVEL_CHOICES, default='info')

    def __unicode__(self):
        return self.body[:50]


#########################################################################################################
# research strands
GOAL_CHOICES = (
     ('A', 'goal A'),
     ('B', 'goal B'),
     ('C', 'goal C'),
     ('D', 'goal D'),
)
class ResearchStrand(models.Model):
    user = models.ForeignKey('auth.User')
    picture = models.ImageField(upload_to='research_strand_imgs', blank=False)
    picture_tag = models.CharField(max_length=200, null=True, blank=False)
    title = models.CharField(max_length=200, null=True, blank=False)
    text = models.TextField(null=True, blank=False)
    upload_date = models.DateField(default=datetime.now().strftime("%Y-%m-%d"), blank=False)
    goal = models.CharField(max_length=1, choices=GOAL_CHOICES, unique=True, blank=True, null=True)

    def __unicode__(self):
        return "{0}".format(self.user.username)


#########################################################################################################
# carousel
class Carousel(models.Model):
    user = models.ForeignKey('auth.User')
    picture = models.ImageField(upload_to='carousel_imgs', blank=False)
    link = models.CharField(max_length=200, null=True, blank=True)
    title = models.CharField(max_length=200, null=True, blank=False)
    text = models.TextField(null=True, blank=False)
    upload_date = models.DateField(default=datetime.now().strftime("%Y-%m-%d"), blank=False)

    def __unicode__(self):
        return "{0}".format(self.user.username)


#########################################################################################################
# publications
from django.utils import timezone
class LabPublication(models.Model):
    user = models.ForeignKey('auth.User')
    title = models.CharField(max_length=300)
    authors = models.CharField(max_length=500)
    journal = models.CharField(max_length=300)
    year = models.IntegerField(blank=True, null=True)
    month = models.IntegerField(blank=True, null=True)
    day = models.IntegerField(blank=True, null=True)
    journal_url = models.URLField(max_length=200, null=True, blank=True)
    pubmed = models.URLField(max_length=200, null=True, blank=True)
    citation = models.TextField(null=True, blank=True)
    mini_citation = models.TextField(null=True, blank=True)
    abstract = models.TextField(null=True, blank=True)
    pdf = models.FileField(upload_to='lab_publications', blank=True)
    picture = models.ImageField(upload_to='lab_publications/img', blank=True)

    def __str__(self):
        return self.title


#########################################################################################################
# user profile
class UserProfile(models.Model):
    user = models.OneToOneField(User)
    picture = models.ImageField(upload_to='lab_profile_imgs', blank=False)
    position = models.CharField(max_length=100, null=True, blank=False)
    bio = models.TextField(null=True, blank=False)
    start_date = models.DateField(default=datetime.now().strftime("%Y-%m-%d"), blank=False)
    end_date = models.DateField(default='2020-01-01', blank=False)

    def __unicode__(self):
        return "{0}".format(self.user.username)


#########################################################################################################
# user profile forms etc.
from django import forms
from django.forms import ModelForm
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    def __init__(self, *args, **kwargs):
        # first call parent's constructor
        super(UserForm, self).__init__(*args, **kwargs)
        # set required fields
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True
        self.fields['groups'].required = True

    class Meta:
            model = User
            fields = ["username", "password", "email", "first_name", "last_name", "groups"]
            error_messages = {
                'password': {
                            'max_length': ("This password is too long!"),
                            },
            }

class UserProfileForm(forms.ModelForm):
        class Meta:
                model = UserProfile
                fields = ["position", "picture", "bio"]
                help_texts = {
                    'picture': ('Please select a pre-cropped photo / photo centred on you.'),
                    'bio': ('Please enter a short biography for the site (500 characters maximum).'),
                }
                error_messages = {
                    'bio': {
                                'max_length': ("The bio is too long! Maximum length = 500 characters"),
                                },
                }


#########################################################################################################
# bioinformatic analyses
class Bioinformatics(models.Model):
    user = models.ForeignKey('auth.User')
    created_date = models.DateTimeField(default=timezone.now)
    title = models.CharField(max_length=300)
    end_user = models.CharField(max_length=300)
    link = models.URLField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    completed = models.BooleanField(default=True)
    archived = models.BooleanField(default=False)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

#########################################################################################################
# tools
class Tools(models.Model):
    user = models.ForeignKey('auth.User')
    picture = models.ImageField(upload_to='research_strand_imgs', blank=False)
    picture_tag = models.CharField(max_length=200, null=True, blank=False)
    title = models.CharField(max_length=200, null=True, blank=False)
    text = models.TextField(null=True, blank=False)
    link = models.URLField(max_length=200, null=True, blank=True)
    upload_date = models.DateField(default=datetime.now().strftime("%Y-%m-%d"), blank=False)

    def __unicode__(self):
        return "{0}".format(self.user.username)

website/web/docker_django/apps/todo/models.py
from __future__ import unicode_literals
import datetime

from django.db import models
from django.contrib.auth.models import User, Group
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone

@python_2_unicode_compatible
class List(models.Model):
    name = models.CharField(max_length=60)
    slug = models.SlugField(max_length=60, editable=False)
    group = models.ForeignKey(Group)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)

        super(List, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def incomplete_tasks(self):
        # Count all incomplete tasks on the current list instance
        return Item.objects.filter(list=self, completed=0)

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Lists"

        # Prevents (at the database level) creation of two lists with the same name in the same group
        unique_together = ("group", "slug")


@python_2_unicode_compatible
class Item(models.Model):
    title = models.CharField(max_length=140)
    list = models.ForeignKey(List)
    created_date = models.DateField(auto_now=True)
    due_date = models.DateField(blank=False, default=timezone.now())
    completed = models.BooleanField(default=None)
    completed_date = models.DateField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='todo_created_by')
    assigned_to = models.ForeignKey(User, blank=True, null=True, related_name='todo_assigned_to')
    note = models.TextField(blank=True, null=True)
    priority = models.PositiveIntegerField()

    # Has due date for an instance of this object passed?
    def overdue_status(self):
        "Returns whether the item's due date has passed or not."
        if self.due_date and datetime.date.today() > self.due_date:
            return 1

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('todo-task_detail', kwargs={'task_id': self.id, })

    # Auto-set the item creation / completed date
    def save(self):
        # If Item is being marked complete, set the completed_date
        if self.completed:
            self.completed_date = datetime.datetime.now()
        super(Item, self).save()

    class Meta:
        ordering = ["priority"]


@python_2_unicode_compatible
class Comment(models.Model):
    """
    Not using Django's built-in comments because we want to be able to save
    a comment and change task details at the same time. Rolling our own since it's easy.
    """
    author = models.ForeignKey(User)
    task = models.ForeignKey(Item)
    date = models.DateTimeField(default=datetime.datetime.now)
    body = models.TextField(blank=True)

    def snippet(self):
        # Define here rather than in __str__ so we can use it in the admin list_display
        return "{author} - {snippet}...".format(author=self.author, snippet=self.body[:35])

    def __str__(self):
        return self.snippet

website/web/docker_django/apps/landing_page/forms.py
from django import forms

class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea)

from .models import LabPublication

class LabPublicationForm(forms.ModelForm):
    class Meta:
        model = LabPublication
        fields = ('user', 'title', 'authors', 'journal', 'year', 'journal_url', 'pubmed', 'citation', 'mini_citation', 'abstract', 'pdf', 'picture')

website/web/docker_django/apps/todo/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User, Group
from .models import Item, List


class AddListForm(ModelForm):
    # The picklist showing allowable groups to which a new list can be added
    # determines which groups the user belongs to. This queries the form object
    # to derive that list.
    def __init__(self, user, *args, **kwargs):
        super(AddListForm, self).__init__(*args, **kwargs)
        self.fields['group'].queryset = Group.objects.filter(user=user)

    class Meta:
        model = List
        exclude = []


class AddItemForm(ModelForm):
    # The picklist showing the users to which a new task can be assigned
    # must find other members of the groups the current list belongs to.
    def __init__(self, task_list, *args, **kwargs):
        super(AddItemForm, self).__init__(*args, **kwargs)
        # print dir(self.fields['list'])
        # print self.fields['list'].initial
        self.fields['assigned_to'].queryset = User.objects.filter(groups__in=[task_list.group])
        self.fields['assigned_to'].label_from_instance = \
            lambda obj: "%s (%s)" % (obj.get_full_name(), obj.username)



    due_date = forms.DateField(
        required=True,
        widget=forms.DateTimeInput(attrs={'class': 'due_date_picker'})
    )

    title = forms.CharField(
        widget=forms.widgets.TextInput(attrs={'size': 35})
    )

    note = forms.CharField(widget=forms.Textarea(), required=False)

    class Meta:
        model = Item
        exclude = []


class EditItemForm(ModelForm):
    # The picklist showing the users to which a new task can be assigned
    # must find other members of the groups the current list belongs to.
    def __init__(self, *args, **kwargs):
        super(EditItemForm, self).__init__(*args, **kwargs)
        self.fields['assigned_to'].queryset = User.objects.filter(groups__in=[self.instance.list.group])

    class Meta:
        model = Item
        exclude = ('created_date', 'created_by',)


class AddExternalItemForm(ModelForm):
    """Form to allow users who are not part of the GTD system to file a ticket."""

    title = forms.CharField(
        widget=forms.widgets.TextInput(attrs={'size': 35})
    )
    note = forms.CharField(
        widget=forms.widgets.Textarea(),
        help_text='Foo',
    )

    class Meta:
        model = Item
        exclude = ('list', 'created_date', 'due_date', 'created_by', 'assigned_to',)


class SearchForm(forms.Form):
    """Search."""

    q = forms.CharField(
        widget=forms.widgets.TextInput(attrs={'size': 35})
    )

website/web/docker_django/apps/landing_page/templates/todo/add_external_task.html
{% extends "landing_page/_base.html" %}
{% load static from staticfiles %}

{% block content %}
    <h2>{{ task }}</h2>

    <form action="" method="POST">
    {% csrf_token %}


    {% if task.note %}
    <div class="task_note"><strong>Note:</strong> {{ task.note|safe|urlize|linebreaks }}</div>
    {% endif %}

    <div id="TaskEdit">
    <h3>File Trouble Ticket</h3>
    <p>Trouble with a computer or other technical system at the J-School? <br />
    Use this form to report the difficulty - we'll get right back to you. </p>

    {% if form.errors %}

        {% for error in form.errors %}
        <ul class="errorlist">
            <li><strong>The {{ error|escape }} field is required.</strong></li>
        </ul>
        {% endfor %}
    <br />

    {% endif %}


    <table>
        {{ form.management_form }}
        {{ form.id }}

    <tr>
        <td>Summary:</td>

        <td>{{ form.title }} <br />
        Include the workstation number in your summary, e.g. <br />
        "Radio Lab # 4: Purple smoke pouring out the back."
         </td>
    </tr>


    <tr>
        <td valign="top">Note:</td>

        <td valign="top">{{ form.note }}<br />
        Please describe the problem.   </td>
    </tr>

    <tr>
        <td>Priority:</td>

        <td>{{ form.priority }} <br />
        Enter a number between 1 and 5, <br />
        where 5 is highest ("Computer is on fire = True").
         </td>
    </tr>

    </table>
    <p><input type="submit" class="todo-button" name="add_task" value="Submit"></p>
    </div>


    </form>


{% endblock %}

website/web/docker_django/apps/landing_page/templates/todo/add_list.html
{% extends "landing_page/_base.html" %}
{% load static from staticfiles %}

{% block content %}
<!-- Header -->
<header id="heading" class="pad-section">
  <div class="container text-center">
				<h1>Add a task list</h1>
  </div>
</header>
<!-- /Header-->

<!-- Content -->
<div class="content-section-b">
  <div class="container">

		<!-- Site messages (for todo lists) -->
    {% if messages %}
        {% for message in messages %}
          <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
              <a href="#" class="close" data-dismiss="alert">&times;</a>
              <strong>{{ message }}</strong>
          </div>
        {% endfor %}
    {% endif %}


	<form action="" method="post">
		{% csrf_token %}

    <table class="table">
      {% if form.errors %}
      <p><strong>Submission error:</strong></p>
      <p>{{form.errors}}</p>
      {% endif %}
       <tr>
           <td><label for="id_title">Task list name:</label> {{ form.name }}</td>
       </tr>
       <tr>
           <td><label for="id_due_date">Group:</label> {{ form.group }}</td>
       </tr>

    </table>
    <p><input type="submit" name="add_task_list" value="Create list!" class="btn btn-default btn-md pull-center hvr-fade"></p>

	<hr>
	<p><a href="{% url 'todo-lists' %}">Back to task lists</a></p>

	</div>
</div>



<!-- footer -->
{% include "landing_page/footer.html" %}
<!-- /footer -->
{% endblock %}

website/web/docker_django/apps/landing_page/templates/todo/list_lists.html
{% extends "landing_page/_base.html" %}
{% load static from staticfiles %}

{% block content %}
<!-- Header -->
<header id="heading" class="pad-section">
  <div class="container text-center">
    <h1>Task manager</h1>
    <h4 class="hidden-xs">Submit/Edit/View bioinformatics projects</h4>
    <a href="{% url 'todo-add_list' %}" class="btn btn-default btn-lg hvr-fade" role="button"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Add task list</a>
  </div>
</header>
<!-- /Header-->

<!-- Content -->
<div class="content-section-b">
  <div class="container">

   <p>Click on an individual list name to add a task or view progress</p>
   <hr/>
   	{% regroup list_list by group as section_list %}

    {% for group in section_list %}
        <h2 style="color: orange;">{{ group.grouper }}</h2>
        <ul>
            {% for item in group.list %}
   	            <li><a class="todo" href="{% url 'todo-incomplete_tasks' item.id item.slug %}">{{ item.name }} </a> ({{ item.incomplete_tasks.count }}/{{ item.item_set.count }})</li>
            {% endfor %}
        </ul>
    {% endfor %}

  </div>
</div>

<!-- footer -->
{% include "landing_page/footer.html" %}
<!-- /footer -->

{% endblock %}

website/web/docker_django/apps/landing_page/templates/todo/view_list.html
{% extends "landing_page/_base.html" %}
{% load static from staticfiles %}

{% block content %}
<!-- Header -->
<header id="heading" class="pad-section">
  <div class="container text-center">
		<!-- ToDo list -->
		{% ifequal list_slug "mine" %}
				<h1>Tasks assigned to {{ request.user }}</h1>
		{% else %}
				{% ifequal auth_ok 1 %}
					 <h1>Tasks filed under "{{ list.name }}"</h1>
					 <h3 style="color:white;">This task list belongs to &rarr; <i>{{ list.group }}</i></h3>
				{% endifequal %}
		{% endifequal %}
  </div>
</header>
<!-- /Header-->

<!-- Content -->
<div class="content-section-b">
  <div class="container">
    <!-- Site messages (for todo lists) -->
    {% if messages %}
        {% for message in messages %}
          <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
              <a href="#" class="close" data-dismiss="alert">&times;</a>
              <strong>{{ message }}</strong>
          </div>
        {% endfor %}
    {% endif %}

    {% ifequal auth_ok 1 %}
        <form action="" method="POST">
        {% csrf_token %}

   {# Only show task adder if viewing a proper list #}
   {% ifnotequal list_slug "mine" %}

   <div class="row">
     <div class="col-lg-2">
     </div>
     <div class="col-lg-8 text-center">
       <div class="panel panel-primary">
            <div class="content-box-header panel-heading">
               <h3 class="panel-title"><i class="fa fa-magnet"></i> Control Panel</h3>
           </div>
           <div class="panel-body">
               <a href="mailto:will.rowe@liverpool.ac.uk?Subject=bioinformatics-admin" target="_top" class="btn btn-default btn-md pull-center hvr-fade"> Email Will </a>
               <a href="{% url 'todo-completed_tasks' list_id list_slug %}" class="btn btn-default btn-md pull-center hvr-fade"> View completed tasks </a>
               <a href="{% url 'todo-lists' %}" class="btn btn-default btn-md pull-center hvr-fade"> Back to task lists </a>
               {% ifequal can_del 1 %}
               {% ifnotequal list_slug "mine" %}
               <a href="{% url 'todo-del_list' list_id list_slug %}" class="btn btn-danger btn-md pull-center"> Delete task list </a>
               {% endifnotequal %}
               {% endifequal %}

               <a class="btn btn-success btn-md pull-center" id="slideToggle"> Add a new task <span class="caret"></span></a>
               <div id="AddTask">
                 <br>
            	    <table class="table">
                    {% if form.errors %}
                    <p><strong>Submission error:</strong></p>
                    <p>{{form.errors}}</p>
                    {% endif %}
            	       <tr>
            	           <td><label for="id_title">Task name:</label> {{ form.title }}</td>
                     </tr>
                     <tr>
            	           <td><label for="id_due_date">Due date:</label> {{ form.due_date }}</td>
                     </tr>
                     <tr>
            	           <td><label for="id_assigned">Assign to:</label> {{ form.assigned_to }}</td>
                     </tr>
            	       <tr>
            	           <td><label for="id_note">Additional task information:</label>
                                {{ form.note }}
            	               <p class="minor"> An email notification will be sent if the task is assigned to someone besides yourself.</p>
            	           </td>
             	       </tr>
            	    </table>
                    <input type="hidden" name="priority" value="999" id="id_priority">
                    <input type="hidden" name="id_notify" value="1" id="notify">
                    <input type="hidden" name="created_by" value="{{ request.user.id }}" id="id_created_by">
                    <input type="hidden" name="list" value="{{ list.id }}" id="id_list">
                    <input type="hidden" name="created_date" value="{{ created_date }}" id="id_created_date">
                  <p><input type="submit" name="add_task" value="Submit task!" class="btn btn-default btn-md pull-center hvr-fade"></p>
                </div>
                {% endifnotequal %}
                {% ifequal view_completed 0  %}
           </div>
       </div>
     </div>
  </div>


  <div class="row">
         <div class="col-lg-12 text-center">
           <p>
           <p>This list is in ranked order - drag a task further up the list to increase its priority!</p>
           <br>
        </div>
  </div>




  <div class="container">
    <table class="table table-hover" id="tasktable">
      <thead>
        <tr>
            <th>Task title</th>
            <th style="text-align:center;">Submitted on</th>
            <th style="text-align:center;">Submitted by</th>
            <th style="text-align:center;">Due on</th>
            {% ifequal list_slug "mine" %}
              <th style="text-align:center;">List</th>
            {% else %}
              <th style="text-align:center;">Assigned to</th>
            {% endifequal %}
            <th style="text-align:center;">Comments</th>
            <th style="text-align:center;">Mark done</th>
        </tr>
      </thead>
      <tbody>
        {% for task in task_list %}
    	        <tr id="{{ task.id }}">
    	            <td><a href="{% url 'todo-task_detail' task.id %}">{{ task.title|slice:":20" }}. . .</a></td>
    	            <td style="text-align:center;">{{ task.created_date|date:"d/m/Y" }}</td>
                  <td style="text-align:center;">{{ task.created_by.first_name }} {{ task.created_by.last_name }}</td>
    	            <td style="text-align:center;">
    	            {% if task.overdue_status %}<span class="overdue">{% endif %}
    	                {{ task.due_date|date:"d/m/Y" }}
    	            {% if task.overdue_status %}</span>{% endif %}
    	            </td>
                  {% ifequal list_slug "mine" %}
                    <td><a href="{% url 'todo-incomplete_tasks' task.list.id task.list.slug %}">{{ task.list }}</a></td>
                  {% else %}
    	               <td style="text-align:center;">{{ task.assigned_to.first_name }} {{ task.assigned_to.last_name }}</td>
                  {% endifequal %}
    	            <td style="text-align:center;">{% ifnotequal task.comment_set.all.count 0  %}{{ task.comment_set.all.count }}{% else %}0{% endifnotequal %}</td>
    	            <td style="text-align:center;"><input type="checkbox" name="mark_done" value="{{ task.id }}" id="mark_done_{{ task.id }}"></td>
                </tr>
    	    {% endfor %}
      </tbody>
    </table>
  </div>



    <div class="row">
           <div class="col-lg-12 text-center">
             <p><input type="submit" name="mark_tasks_done" value="Update task table" class="todo-button"></p>
          </div>
    </div>


    {% endifequal %}





    {% ifequal view_completed 1 %}
	<h3>Completed tasks</h3>
    <table class="table table-hover" id="tasktable">
        <tr>
            <th style="text-align:center;">Task</th>
            <th style="text-align:center;">Created</th>
            <th style="text-align:center;">Completed on</th>
            <th style="text-align:center;">Undo</th>
        </tr>
		{% for task in completed_list %}
	        <tr>
	            <td><a href="{% url 'todo-task_detail' task.id %}">{{ task.title|truncatewords:20 }}</a></td>
	            <td>{{ task.created_date|date:"d/m/Y" }}</td>
	            <td>{{ task.completed_date|date:"d/m/Y" }}</td>
	            <td><input type="checkbox" name="undo_completed_task" value="{{ task.id }}" id="id_undo_completed_task{{ task.id }}">   </td>
            </tr>
	    {% endfor %}
	</table>
	<p><input type="submit" name="deldonetasks" value="Update this table"  class="todo-button"></p>
	</form>
    <p><a  class="todo" href="{% url 'todo-incomplete_tasks' list_id list_slug %}">Back to task list</a></p>
    {% endifequal %}

    {% endifequal %}

  </div>
</div>



<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/flick/jquery-ui.css" />

<!-- CSS and JavaScript for django-todo -->
<script type="text/javascript" charset="utf-8">
    // thedate.x comes from the edit_task view. If this is a new entry,
    // thedate won't be present and datepicker will fall back on the default (today).
    $(document).ready(function(){
        $('#id_due_date').datepicker({ dateFormat: 'dd/mm/yy' });
     });
</script>

<script type="text/javascript">
    function order_tasks(data) {
        // The JQuery plugin tableDnD provides a serialize() function which provides the re-ordered
        // data in a list. We pass that list as an object called "data" to a Django view
        // to save the re-ordered data into the database.
        $.post("{% url 'todo-reorder_tasks' %}", data, "json");
        return false;
    };
    $(document).ready(function() {
        // Initialise the task table for drag/drop re-ordering
        $("#tasktable").tableDnD();
        $('#tasktable').tableDnD({
            onDrop: function(table, row) {
                order_tasks($.tableDnD.serialize());
            }
        });
        // Initially hide the Add Task form
        $('#AddTask').hide();
        // toggle slide to show the Add Task form when link clicked
        $('#slideToggle').click(function(){
            $(this).siblings('#AddTask').slideToggle();
        });
    });
</script>


{% endblock %}